import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

export const onRequest = async (context: any) => {
  try {
    // Log environment availability for debugging
    console.log('[Pages Function] Request received:', {
      url: context.request.url,
      method: context.request.method,
      hasEnv: !!context.env,
      hasLogsBucket: !!(context.env?.LOGS_BUCKET),
      envKeys: context.env ? Object.keys(context.env) : [],
    });

    // Dynamic import to avoid bundling issues during Cloudflare's Functions build
    // The server build is generated by `remix vite:build` and needs to be loaded at request time
    // @ts-ignore - build/server is generated at build time
    const build = await import("../build/server");

    console.log('[Pages Function] Remix build loaded successfully');

    const handler = createPagesFunctionHandler({
      build,
      getLoadContext: (ctx: any) => {
        const loadContext = {
          // Provide env at top level for direct access
          env: ctx.env,

          // Also provide under cloudflare namespace for compatibility
          cloudflare: {
            env: ctx.env,
            cf: ctx.request?.cf,
            ctx: ctx.waitUntil?.bind(ctx),
            caches: caches,
          },
        };

        console.log('[Pages Function] Load context created:', {
          hasEnv: !!loadContext.env,
          hasLogsBucket: !!(loadContext.env?.LOGS_BUCKET),
        });

        return loadContext;
      },
    });

    console.log('[Pages Function] Handler created, calling Remix handler...');
    const response = await handler(context);
    console.log('[Pages Function] Handler response:', response.status);

    return response;
  } catch (error) {
    console.error('[Pages Function] Unhandled error:', {
      message: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
      error: error,
    });

    // Return a proper error response
    return new Response(
      JSON.stringify({
        error: 'Internal Server Error',
        message: error instanceof Error ? error.message : 'An unexpected error occurred',
        timestamp: new Date().toISOString(),
      }),
      {
        status: 500,
        headers: {
          'Content-Type': 'application/json',
        },
      }
    );
  }
};
