name = "project-monitoring"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "cloudflare-managed-2ff00513"
preview_bucket_name = "cloudflare-managed-2ff00513"

[vars]
ACCESS_TOKEN = "logs_viewer_7a8f3e2c9b5d1f4a6e8c3b7d9f2a5e1c"
