name = "project-monitoring"
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "cloudflare-managed-2ff00513"
preview_bucket_name = "cloudflare-managed-2ff00513"

[vars]
ADMIN_USERNAME = "admin"
