import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

export const onRequest = async (context: any) => {
  // Dynamic import to avoid bundling issues during Cloudflare's Functions build
  // The server build is generated by `remix vite:build` and needs to be loaded at request time
  const build = await import("../build/server");

  const handler = createPagesFunctionHandler({
    // @ts-expect-error - Build type is inferred from dynamic import
    build,
    getLoadContext: (ctx: any) => ({
      // Provide env at top level for direct access
      env: ctx.env,

      // Also provide under cloudflare namespace for compatibility
      cloudflare: {
        env: ctx.env,
        cf: ctx.request?.cf,
        ctx: ctx.waitUntil?.bind(ctx),
        caches: caches,
      },
    }),
  });

  return handler(context);
};
